import { RecoveryTracker } from './recovery';
import type { PodView } from './types';

function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function pod(uid: string, owner = 'rs-1', ready = false, extra: Partial<PodView> = {}): PodView {
  return { uid, name: uid, namespace: 'payments', node: 'node-1', phase: 'Running', ready, restartCount: 0, reason: '', cpuMillis: 10, memMib: 16, createdAt: '2026-09-10T12:00:00.000Z', deletionTimestamp: '', controller: { apiVersion: 'apps/v1', kind: 'ReplicaSet', name: 'api', uid: owner }, ...extra };
}
function setup(target = pod('old'), pods: PodView[] = [target]) {
  let now = 100; const tracker = new RecoveryTracker(() => now); const operation = tracker.begin(target, pods);
  return { tracker, operation, setNow: (value: number) => { now = value; } };
}
export function testObservedRecovery() {
  const { tracker, operation, setNow } = setup(pod('old', 'rs-1', false), [pod('old', 'rs-1', false), pod('existing', 'rs-1', true)]);
  tracker.accepted(operation.id); assert(operation.phase === 'accepted', 'HTTP acceptance is not deletion');
  tracker.observe({ type: 'updated', pod: pod('existing', 'rs-1', true) }); assert(operation.candidateUid === undefined, 'existing sibling is not a replacement');
  setNow(200); tracker.observe({ type: 'deleted', uid: 'old' }); setNow(300); tracker.observe({ type: 'added', pod: pod('new') }); setNow(1200); tracker.observe({ type: 'updated', pod: pod('new', 'rs-1', true) });
  assert(String(operation.phase) === 'ready', 'new candidate must become Ready'); assert(operation.readyObservedAt! - operation.startedAt === 1100, 'observed duration differs');
}
export function runRecoveryTests() {
  testObservedRecovery();
  { const { tracker, operation } = setup(); tracker.accepted(operation.id); assert(operation.phase === 'accepted', '202 without watch stays accepted'); }
  { const { tracker, operation } = setup(); tracker.accepted(operation.id); tracker.observe({ type: 'updated', pod: pod('old', 'rs-1', false, { restartCount: 1 }) }); assert(operation.phase === 'accepted' && operation.message === 'Restart observed; target UID is unchanged', 'same UID restart is not a replacement'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.accepted(operation.id); assert(operation.phase === 'absent' && operation.absentAt === 100, 'watch before 202 does not regress'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('new') }); tracker.observe({ type: 'updated', pod: pod('new', 'rs-1', true) }); tracker.observe({ type: 'deleted', uid: 'new' }); assert(operation.phase === 'absent' && operation.candidateUid === undefined, 'deleted candidate cannot remain Ready'); }
  { const { tracker, operation } = setup(); tracker.accepted(operation.id); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('new', 'rs-1', true) }); tracker.observe({ type: 'snapshot', pods: [pod('old'), pod('new', 'rs-1', true)] }); assert(operation.phase === 'accepted' && operation.absentAt === undefined && operation.readyObservedAt === undefined, 'snapshot target membership revokes stale absence and Ready timing'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('new', 'rs-1', true) }); assert(operation.phase === 'ready', 'candidate first reaches Ready'); tracker.observe({ type: 'snapshot', pods: [] }); assert(String(operation.phase) === 'absent' && operation.candidateUid === undefined && operation.readyObservedAt === undefined, 'snapshot omission revokes stale candidate Ready'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'added', pod: pod('new', 'rs-1', true) }); tracker.observe({ type: 'deleted', uid: 'old' }); assert(String(operation.phase) === 'ready', 'candidate before deletion can be observed Ready'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('new', 'rs-1', true) }); assert(operation.phase === 'ready', 'Ready on first candidate event is observed'); }
  { const { tracker, operation, setNow } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('new', 'rs-1', true) }); const readyAt = operation.readyObservedAt; setNow(200); tracker.accepted(operation.id); assert(operation.phase === 'ready' && operation.acceptedAt === 200 && operation.readyObservedAt === readyAt, 'late acceptance records evidence without regressing observed Ready timing'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('foreign-owner', 'other', true) }); tracker.observe({ type: 'added', pod: pod('foreign-ns', 'rs-1', true, { namespace: 'other' }) }); assert(operation.phase === 'absent', 'foreign owner and namespace do not correlate'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('rollout-a') }); tracker.observe({ type: 'added', pod: pod('rollout-b') }); assert(operation.phase === 'ambiguous', 'two candidate UIDs stay ambiguous'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('new', 'rs-1', true) }); tracker.observe({ type: 'added', pod: pod('late') }); assert(operation.phase === 'ambiguous' && operation.readyObservedAt === undefined, 'later competing evidence reclassifies historical Ready'); }
  { const { tracker, operation } = setup(); tracker.connection(false); tracker.connection(true); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'snapshot', pods: [pod('old-brother', 'rs-1', true)] }); assert(String(operation.phase) === 'ready' && operation.observationIncomplete && operation.readyObservedAt === undefined && operation.message.includes('latest snapshot'), 'gap cannot establish old sibling creation'); }
  { const target = pod('solo', 'rs-1', false, { controller: null }); const { operation } = setup(target); assert(operation.phase === 'standalone', 'standalone has no replacement promise'); }
  { const target = pod('job-old', 'job-1', false, { controller: { apiVersion: 'batch/v1', kind: 'Job', name: 'batch', uid: 'job-1' } }); const { tracker, operation } = setup(target); tracker.observe({ type: 'deleted', uid: target.uid }); tracker.observe({ type: 'added', pod: pod('job-new', 'job-1', true, { controller: target.controller }) }); assert(operation.phase === 'candidate', 'Job readiness is not a replacement promise'); }
  { const target = pod('db-0', 'sts', false, { controller: { apiVersion: 'apps/v1', kind: 'StatefulSet', name: 'db', uid: 'sts' } }); const { tracker, operation } = setup(target); tracker.observe({ type: 'deleted', uid: target.uid }); tracker.observe({ type: 'added', pod: pod('db-1', 'sts', true, { controller: target.controller }) }); assert(String(operation.phase) === 'absent', 'StatefulSet requires same name'); tracker.observe({ type: 'added', pod: pod('new-db-0', 'sts', true, { name: 'db-0', controller: target.controller }) }); assert(String(operation.phase) === 'ready', 'StatefulSet same name is eligible'); }
  { const target = pod('ds-old', 'ds', false, { controller: { apiVersion: 'apps/v1', kind: 'DaemonSet', name: 'agent', uid: 'ds' } }); const { tracker, operation } = setup(target); tracker.observe({ type: 'deleted', uid: target.uid }); tracker.observe({ type: 'added', pod: pod('ds-other', 'ds', true, { node: 'node-2', controller: target.controller }) }); assert(operation.phase === 'absent', 'DaemonSet requires same node'); }
  { const { tracker, operation } = setup(); tracker.observe({ type: 'deleted', uid: 'old' }); tracker.observe({ type: 'added', pod: pod('terminating', 'rs-1', true, { deletionTimestamp: '2026-09-10T12:01:00.000Z' }) }); assert(operation.phase === 'absent', 'terminating candidate cannot become Ready'); }
  { const { tracker, operation, setNow } = setup(); tracker.connection(false); tracker.connection(true); setNow(800); tracker.observe({ type: 'snapshot', pods: [] }); assert(String(operation.phase) === 'absent' && operation.absentAt === undefined, 'snapshot absence has no historical time'); tracker.observe({ type: 'snapshot', pods: [pod('new', 'rs-1', true)] }); assert(String(operation.phase) === 'ready' && operation.readyObservedAt === undefined && operation.message.includes('latest snapshot'), 'snapshot Ready has no exact timing'); }
  { const { tracker, operation, setNow } = setup(); setNow(60_100); assert(tracker.operations[0].message === 'Still waiting; recovery is not confirmed', '60 second wait remains observable'); tracker.observe({ type: 'snapshot', pods: [pod('old')] }); assert(operation.startedAt === 100, 'snapshot never restarts duration'); }
  { const { tracker, operation } = setup(); assert(tracker.begin(pod('old'), [pod('old')]) === operation && tracker.operations.length === 1, 'open duplicate is blocked'); tracker.dismiss(operation.id); assert([...tracker.operations].length === 0, 'dismiss only removes tracking'); }
  { const targetA = pod('a'), targetB = pod('b'); const tracker = new RecoveryTracker(() => 100); const a = tracker.begin(targetA, [targetA, targetB]); const b = tracker.begin(targetB, [targetA, targetB]); assert(a.phase === 'ambiguous' && b.phase === 'ambiguous', 'two ReplicaSet targets are ambiguous'); }
  { const controller = { apiVersion: 'apps/v1', kind: 'StatefulSet', name: 'db', uid: 'sts' }; const targetA = pod('db-0', 'sts', false, { controller, name: 'db-0' }); const targetB = pod('db-1', 'sts', false, { controller, name: 'db-1' }); const tracker = new RecoveryTracker(() => 100); const a = tracker.begin(targetA, [targetA, targetB]); const b = tracker.begin(targetB, [targetA, targetB]); assert(a.phase === 'requesting' && b.phase === 'requesting', 'distinct StatefulSet identities do not conflict'); }
  { const tracker = new RecoveryTracker(() => 100); for (let index = 0; index < 21; index++) { const target = pod('old-' + index, 'owner-' + index); const operation = tracker.begin(target, [target]); tracker.failed(operation.id, 'no', false); } assert(tracker.operations.length === 20, 'only the oldest closed operation is pruned'); }
}
